### ISSUE TITLE
Allow deep link to be opened in a new tab

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1211]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to open some links in a new tab.
**Acceptance Criteria**

- [ ] Follow Project DOD
- [ ] ctl+click or right click and open in a new tab works - the user is directed to the deep link
- [ ] This feature will work with LocalStorage Kubeconfig only ( its acceptable to not work with the other storage types )

**Comment by Wawrzyn321** [comment]
I've started looking into it, but didn't get far:
* We have 2 Link components in our codebase - `Link` from fd-react & `Link` from our shared, that acts like an external link. Would be nice to rename the latter to `ExternalLink` so it's easier to reason. We could also have one `Link` component, with `external` prop.
* I'm not sure if we can use builtin "Open in a new tab" functionality - we need to use Luigi's `LuigiClient.linkManager().newTab().navigate(<link>);` - note the `newTab()` part. If we just use `<a href="#"`, it will open the inner frame in the new tab, instead of entire Luigi app.

**Comment by mrCherry97** [comment]
`window.location` is working on Chrome, but didn't work on Firefox, we are parking that topic since removing Luigi https://github.com/kyma-project/busola/issues/1257

**Comment by mrCherry97** [comment]
After removing Luigi we have this functionality.
![image](https://user-images.githubusercontent.com/46759954/210509654-a5e4d41c-4a77-4d97-9936-64866779395d.png)
![image](https://user-images.githubusercontent.com/46759954/210509695-80e649e0-613b-47a3-9b02-7c7f18cd9c11.png)
