### ISSUE TITLE
SPIKE: Evaluate Datree.io can be run as a WASM plugin

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1255]
**Description**

Evaluate Datree.io can be run as a WASM plugin to validate our yaml files before are sent to the server

**Reasons**

We continually look for ways to support our user and help them be comfortable to pus k8s changes. We need to evaluate if we can use a validation tool like Datree.io to validate yaml / application before are being sent to k8s.

**Target**
- 2-3 Days MD

**Attachments**

- https://github.com/datreeio/datree

**Comment by Lyczeq** [comment]
After exploring this topic I think we shouldn't use Datree.io but try to write our own solution based on the YAML [schema](https://github.com/datreeio/datree/blob/main/pkg/defaultRules/defaultRules.yaml) they use.

Thoughts of using Datree as a WASM plugin:
- Additional Go codebase that we have to maintain (updating libraries before releases etc.). What is more, if a developer doesn't know Go it is more difficult to contribute or fix a bug in this part of the code.
- I contacted with Datree guys via their slack channel and I was told that they don't officially support using datree as importable go packages so it might break in the upcoming versions.
- I guess it would be more challenging to adjust translations

Thoughts of writing our own solution in Javascript:
- Since we have a schema they use, we can write our own solution using JS that is used in all busola.
- More control over the code
- There is a probability that JS solution won't be as fast as a wasm plugin

**Comment by Lyczeq** [comment]
After a talk, we decided to implement the solution using Javascript and the [schema](https://github.com/datreeio/datree/blob/main/pkg/defaultRules/defaultRules.yaml) from the Datree repository with the following JSON Schema [engine](https://github.com/ExodusMovement/schemasafe). It gives us more control of the code than writing a fancy WASM plugin in e.g. Golang that we would maintain. The implementation will be done in the following [PR](https://github.com/kyma-project/busola/issues/1445).
