### ISSUE TITLE
SPIKE: Run Busola without Luigi

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1257]
**Description**

The scope of the POC is to try to run Busola without Luigi, and evaluate what would be the effort to do so

**Acceptance Crieria**

- We have a POC running Busola without Luigi  that provides login functionalities too
- Visual Consistency is not that important
- Documenting the issues/effort is the main task, POC is 
- Service Catalog is not part of this

**Target Timing**
- 6 MD ( 2*3MD )

**Comment by dariadomagala** [comment]
Luigi has been added in [this PR](https://github.com/kyma-project/console/commit/35238a983faefc67c31c43d8c37847250b1099d8) maybe someone will find it useful to see the differences and the previous implementation

**Comment by Wawrzyn321** [comment]
So... what are the responsibilities of `core` and `Luigi` in our little app?

* Rendering navigation, context/product switcher, footer etc. - this is the fun part actually
* Microfrontend modals - these should be easily handled with our current `core-ui` modals.
* Auth - SSO & k8s, Luigi uses [openid-client](https://www.npmjs.com/package/openid-client), we can reuse that. Would be nice to finally have silent token refresh instead of page refresh.
* Cluster handshake - making initial calls, checking if CA is required - should be moved to a context I guess
* Resolving features - again let's move everything into context
* Caching the initial & feature calls - this could be dropped for that PoC
* Kubeconfig ID

And don't forget about the usage of LuigiClient in the `core-ui`

* Navigation with contexts - we would need to build the paths ourselves
* Context - as mentioned above
* CustomMessages - won't be needed

**Comment by Wawrzyn321** [comment]
About navigation - Catalog won't work for now.

**Comment by Wawrzyn321** [comment]
All work done during this spike is on https://github.com/Wawrzyn321/busola/tree/no-luigi

We would need one more spike to choose a solid state management system for clusters, auth, init calls, features, settings (basically everything what Luigi has done for us), e.g. Redux or contexts.

The final task is rather impossible to split, and we cannot remove Luigi gradually.


So the proposed plan is:
1) Execute the state management spike (todo rzuć tu linka) - the expected result is a choice (Redux or contexts?) and PoC of implementation.
2) Implement the solution from the spike - handle clusters, auth, features, settings.
3) Tasks that can be parallelized:
	* Left navigation - layout
	* Top navigation - product switcher, context switcher
	* Move metadata (apiPath, category, etc.) to component files, layout etc
	* Modal (confirmation modal, preferences modal)
	* Replace LuigiClient navigate functions with React Router ones
5) Adjust e2e tests

To do during the steps or to adjust after finishing them:
	* Kubeconfig ID
	* Behaviours like saving the last visited view, setting the current cluster when the name is present in URL

**Comment by dariadomagala** [comment]
5. Extensibility topic
