### ISSUE TITLE
Monaco validation problems with regex and empty strings

### ISSUE THREAD

**Issue by mrCherry97** [kyma-project/busola#1639]
**Description**
In some cases, Monaco isn't displaying information about the warning in empty strings (for example OAuth2) and regex in APIRules isn't correct.

**Expected result**
When the user clicks Create and goes to YAML there are no warnings.

**Actual result**
OAuth2:
![image](https://user-images.githubusercontent.com/46759954/180166058-d66c0085-7923-4884-9167-23aa0d435466.png)
APIRules:
![image](https://user-images.githubusercontent.com/46759954/180166302-12612e53-0dab-4bf9-a9f4-4020eb6e0f9b.png)
the host is correct, but validation is displaying a warning.

**Steps to reproduce**

**Troubleshooting**

**Comment by dariadomagala** [comment]
1. Monaco validates it properly. Sometimes it shows an error for an empty string because it doesn't match the required regex, and sometimes it doesn't show errors because there is no other requirement other than that it must be a string (and `''` is a valid string).
2. The regex from the API rule comes from the custom resource definition, Monaco understands it correctly and it should show the warning (other tools also mark it as a string that doesn't match the regex). If the regex is wrong, it should be fix on a CRD level by the Kyma team.
