### ISSUE TITLE
Deployment editor adds field with incorrect syntax

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/busola#2429]
**Description**
Deployment editor should not produce yaml that cannot be saved. When you edit the deployment the editor is populated with the field `spec.template.metadata.creationTimestamp: null`. The null value is invalid, therefore you cannot save the changes until you remove that line.

**Expected result**
Editor doesn't introduce incorrect syntax to working deployment.

**Actual result**

<img width="1216" alt="Screenshot 2023-04-07 at 10 35 39" src="https://user-images.githubusercontent.com/191769/230575531-99264506-8db5-41b4-b7be-9405a90bc124.png">

**Steps to reproduce**

Create a new deployment, save it, and then edit it.

**Comment by akucharska** [comment]
Deployment editor works as intended. We do not add `spec.template.createTimestamp`, it is added automatically after the resource creation (the same thing happens when we create from kubectl)

Validation is made based on schema we automatically get from current cluster (we use openapi) where `createTimestamp` is set as a `date-time` type which has a `type: string`.  oreover, this validation does not block updating... it is just a suggestion.
