### ISSUE TITLE
UXC: Tables

### ISSUE THREAD

**Issue by mrCherry97** [kyma-project/busola#3011]
**Description**
- [x] Inactive Tables should have a normal cursor. https://github.com/kyma-project/busola/pull/3085
- [x] The names of table items shouldn’t be a link, because the whole rows are navigateable. (To discuss)
- [x] The orange lock icon should be clickable and a popover should appear, instead of having this hover interaction.
- [x] The locker of the protected resource should be next to the name instead of the special column.
- [x] When the Table is interactive, the cursor should be settled on the pointer https://github.com/kyma-project/busola/pull/3085

**Reasons**
UX review.

**Attachments**
[Figma](https://www.figma.com/board/G7ZWGVCaUXSNNjt0tkuyOQ/UXC-Reviews-2024?node-id=104-542&t=1D8Oufaahl7KFEsN-0)

**Comment by vicslavova** [comment]
The **Name**/identifier of table items shouldn’t be a link if clicking on the row opens flexible column layout. Use link styling when the link sends to an external page or is navigating the user to a different area inside the Kyma dashboard. 
If there is no flexible column layout and the name of the row is a link that opens another page, don't make the whole row clickable, only the link.

In all Kyma tables the names of the items are still links, we would suggest changing them to just black bold text since in this case the whole row is clickable and opens a second column. The only exception is the Namespaces table where we suggest to keep the link, remove the hover of the whole row and make only the link clickable. 

Another example of this is the Events table - there the name should be changed to normal text styling, but we also have the "Involved Object" as a link and this is okay since it navigates to a different page.
