### ISSUE TITLE
Add second badge for modules status

### ISSUE THREAD

**Issue by OliwiaGowor** [kyma-project/busola#3119]
**Description**
Currently only one badge with status for modules is displayed, and it's being taken directly from the module. 
![Image](https://github.com/user-attachments/assets/241610fb-4642-45a7-807c-d892578f5581)

There is also available second status from the Kyma CR and they can be different in some cases.
So to eliminate any confusion for the user, the proposition is to add second State badge if the statuses from Module and Kyma CR are different.

Example: 
When a user tries to delete a module and an error occurs, the module status displays a "Warning" state:
![Image](https://github.com/user-attachments/assets/ec4448bf-5d69-4fe3-adf8-e9e81cc4d35a)

Meanwhile, Kyma CR has a "Deleting" state for the same module:
![Image](https://github.com/user-attachments/assets/8d6f308e-0099-44b1-a2e3-2fa2a11eef6c)

In this case the lack of information about ongoing deletion can be misleading.

**Comment by pbochynski** [comment]
We should display both statuses in case of different statuses from Kyma CR and module CR. 
Another problem is that the status in Kyma CR can be outdated when the module is under deletion due to asynchronous processing by Lifecycle Manager (see also the bug: https://github.com/kyma-project/lifecycle-manager/issues/1762). When the module is removed from the spec section of Kyma CR, it is already in the deleting state, even though the status for that module is still Ready. Fixing the [bug](https://github.com/kyma-project/lifecycle-manager/issues/1762) will make the problem less visible, but it will not disappear - should see immediately the status change to deleting when they removed the module from the Kyma CR spec section.
