### ISSUE TITLE
Inconsistent module status presentation across busola

### ISSUE THREAD

**Issue by arturskorupa** [kyma-project/busola#3458]
**Description**

Busola presents module status on 2 views - one is rendered after one click edit modules on an overview page - there the status of modules is correct. Another is accessible from the path "kyma-system namespace view -> Kyma resource -> default" and there the status is wrong (it's taken from Kyma CR instead of module manifests) 

**Expected result**

Status should be presented consistenlty across the application and it should be like on edit module view (accessible from the cluster overview page)

**Comment by mrCherry97** [comment]
hi @arturskorupa 
this view is generated via Extensibility, and its `Installation state` is taken from Kyma CR (because you are on the Kyma resource view). To display the modules' status, we need to dynamically fetch all the installed modules, which is impossible right now. We will take a look if it's possible to add a custom function to fetch dynamically this data from all of the modules, if it is problematic, then we will change the name of the column to `Installation State` as it is on the Modules view.

**Comment by mrCherry97** [comment]
hi @arturskorupa  
Changes have been pushed to the dev and stage. Please double-check, and if the problem appears one more time, please reopen an issue or contact us.

Best regards,
Mateusz
