### ISSUE TITLE
Unify statuses

### ISSUE THREAD

**Issue by akucharska** [kyma-project/busola#731]
Try to unify statuses from btp-instance, functions and pods. M

**Acceptance Criteria**

- [ ] Follow Project DOD
- [ ] Change resource-specific statuses to something more generic
- [ ] Make sure to display tooltips with the original explanation
- [ ] Consult changes with Grzegorz and the team

**Example**
On new btp instances change translation for status `btp-instances.statuses.createfailed` from `Create Failed` to `Error`. Add or adjust existing tooltip `btp-instances.tooltips.createfailed` to be 'Create Failed'. Make sure we also add error msg if necessary.

**Proposition**
```
btp-instances:
    createfailed: Create Failed -> Error
functions:
    new-revision-error: New Revision Error -> Error
    unhealthy: Unhealthy -> Error
pods: 
    completed: Completed
    containercreating: Container Creating -> Initializing
    containersnotinitialized: Containers Not Initialized -> Error
    containersnotready: Container Not Ready -> Initializing???
    crashloopbackoff: Crash Loop Back-off -> Error
    createcontainerconfigerror: Create Container Config Error -> Error
    createcontainererror: Create Container Error -> Error
    dockerdaemonnotready: Docker Daemon Not Ready -> Initializing??
    errimageneverpull: Image Never Pulled -> ???
    errimagepull: Image Pull Error -> Error
    error: Error
    evicted: Evicted
    imageinspecterror: Image Inspect Error -> Error
    imagepullbackoff: Image Pull Back-off  -> Error
    invalidimagename: Invalid Image Name -> Error
    networkpluginnotready: Network Plugin Not Ready -> Error
    podinitializing: Pod initializing -> Initializing
    poststarthookerror: Post-start Hook Error  -> Error
    registryunavailable: Registry Unavailable -> Error
    runcontainererror: Run Container Error -> Error
    running: Running
    terminated: Terminated
    terminating: Terminating
```

**Comment by akucharska** [comment]
https://github.com/kyma-project/busola/issues/620

**Comment by dariadomagala** [comment]
Does `Unhealthy` in functions really mean there's an error? I think `Pending` is more accurate here.

**Comment by dariadomagala** [comment]
https://github.com/kyma-project/busola/pull/748/

**Comment by kwiatekus** [comment]
@dariadomagala 
> Does `Unhealthy` in functions really mean there's an error? I think `Pending` is more accurate here.

Agree.
That doesnt mean its an error. It means that minimum number of replicas is not available.
It could be because of two states:
 - its not ready YET ( kubernetes sees that its not ready yet - Pending is 100% accurate here )
 - readiness probes started to fail on the pods - so the function suddenly becomes unhealthy. But from k8s point of view is the same state - minimum replicas unavailable. Here Pending is not 100% accureate but I'd say good enough.
 
 The effort of ( estimated to 8 SP ) to [distinguish between initially pending and unhealthy](https://github.com/kyma-project/kyma/issues/12777) doesn't seem to be justify it.
 I'd say lets stick to pending in both those situations
 
 Also the second state ( unhealthy ) is not likely to happen that often because of adjusting runtime presets
 https://github.com/kyma-project/kyma/pull/13226
 
 CC: @moelsayed
