### ISSUE TITLE
Busola incorrectly handles missing skr-configmap

### ISSUE THREAD

**Issue by koala7659** [kyma-project/busola#811]
**Description**

There is a config map created within Kyma named`skr-configmap` when Kyma is installed in SKR managed mode. This config map is missing when Kyma is installed in standalone Kyma OS mode.  Busola requires that this map is always present and reports errors in JS console when it is missing.

**Expected result**

Busola should handle correctly missing `skr-configmap` in Applications tabs in KymaOS scenario. 

**Actual result**

When Opened Applications tab in Busola I can see multiple errors in JS console about missing `skr-configmap`.

![image](https://user-images.githubusercontent.com/18568025/149508283-876ee6a1-3266-4c98-8b49-9aba66cd1587.png)

**Steps to reproduce**

1. Open Busola in KymaOS
2. Go to Integrations-> Applications tab
3. Create some applications
3. Open JS console

**Version information**

Browser Version: MacOS Chrome 96.0.4664.110 (x86_64)
Kyma version: Kyma OS 2.0.2
Kyma Dashboard Version: fe0b344f

**Comment by wchrapka** [comment]
This error is a standard for a failed request. We send a request to determine if it is SKR. Best if we could know that without querrying the server. Otherwise, to hide it, we would need to spoof a response at proxy, which sounds bad. 
However, the error was displayed three times, going to optimize the code to send only 1 request.
