### ISSUE TITLE
[SPIKE] Improve the speed of Cypress tests

### ISSUE THREAD

**Issue by Sawthis** [kyma-project/busola#839]
**Description**

Now our tests on k3d cluster takes around 25-30 minutes. We should try to decrease this time to 10 minutes by:

- [x] Use nkyma to deploy Busola in the namespace? or other long living cluster
- [x] #912
- [ ] Extract the most important tests, and run all only locally and before upgrading stage environment
- [ ] Run periodic job with all tests every night and enable notification on Slack channel.
- [x] Fail the whole suite if the first test fails.
- [ ] At the end after CI/CD flow improvements we should prepare high level diagram about our CI/CD flow.

**Reasons**

Testing PRs and review of them takes way too much time.

**Comment by dariadomagala** [comment]
My thoughts:

- add higher default timeouts - in theory, it will cause the tests to run longer if there is a problem, but it will also cause fewer issues of elements not displayed yet.
- fail the whole suite if the first test fails - it sounds good, but I can see an issue if the problem occurs in the middle, and because of that, we won't run the test last that has a deletion step. That will cause a lot of resources created and not deleted on a cluster. 🙅

**Comment by Sawthis** [comment]
https://github.com/kyma-project/busola/issues/893

**Comment by wchrapka** [comment]
Fail the whole suite if the first test fails. --> a solution is already merged [887](https://github.com/kyma-project/busola/pull/887)
--
I think that would be fire, if we could set multiple machines/threads
https://docs.cypress.io/guides/guides/parallelization#Overview
