### ISSUE TITLE
Make a list of frequently failing test suites

### ISSUE THREAD

**Issue by mrCherry97** [kyma-project/busola#866]
**Description**
To improve better testing and repair failing tests we have to make a list of tests that are failing not randomly.

**Acceptance criteria**
- [ ] Links to failed jobs

**Comment by dariadomagala** [comment]
Jobs failing on the post-master jobs in the past (around) 10 days:

| Test name |	Error |	Prow link |
|----|-----|----|
|  :exclamation: test-issuers.spec.js | Expected to find element: `:visible`, but never found it. Queried from element: \<iframe> |	https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/post-busola-integration-test-k3s/1484467850713239552  |
| test-issuers.spec.js	| Expected to find element: `:visible`, but never found it. Queried from element: \<iframe>	| https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/post-busola-integration-test-k3s/1484165349300506624 |
| test-issuers.spec.js	| Expected to find element: `:visible`, but never found it. Queried from element: \<iframe> |	https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/post-busola-integration-test-k3s/1484133140476727296 |
| test-issuers.spec.js 	| Expected to find element: `:visible`, but never found it. Queried from element: \<iframe>	| https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/post-busola-integration-test-k3s/1486290589472264192 |
|  :exclamation: run-after.spec.js |	Expected not to find content: 'test-mock-app-a-busola-test-2405' within the element: <body> but continuously found it. |	https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/post-busola-smoke-test-docker/1486282537113227264 |
| run-after.spec.js |	Expected not to find content: 'test-mock-app-a-busola-test-5755' within the element: <body> but continuously found it |	https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/post-busola-integration-test-k3s/1484486465512542208  |
| run-after.spec.js 	| Expected not to find content: 'test-mock-app-a-busola-test-2756' within the element: <body> but continuously found it |	https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/post-busola-integration-test-k3s/1484458790404231168 |
| run-after.spec.js 	| Expected not to find content: 'test-mock-app-a-busola-test-2756' within the element: <body> but continuously found it |	https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/post-busola-smoke-test-docker/1484120049307357184 | 
| :grey_exclamation: in-cluster-eventing.spec.js | https://in-cluster-eventing-publisher-9272.nkyma.kyma-prow.shoot.canary.k8s-hana.ondemand.com/ The response we received from your web server was: 404: Not Found |	https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/post-busola-integration-test-k3s/1486653699655733248 |
| in-cluster-eventing.spec.js | https://in-cluster-eventing-publisher-9091.nkyma.kyma-prow.shoot.canary.k8s-hana.ondemand.com/ The response we received from your web server was: 404: Not Found | 	https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/post-busola-integration-test-k3s/1485623178045689856 |
| in-cluster-eventing.spec.js |	Expected to find content: 'order.canceled.v2' within the element: <body> but never did. |	https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/post-busola-integration-test-k3s/1486298643500634112 |
| in-cluster-eventing.spec.js 	| This element `<a.fd-nested-list__link.is-selected.svelte-ih66xe>` is not visible because its parent `<ul.fd-nested-list.fd-nested-list--text-only.level-2.svelte-ih66xe>` has CSS property: `display: none` |	https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/post-busola-integration-test-k3s/1486255351429861376 |
| test-command-palette.spec.js |	`cy.click()` failed because the center of this element is hidden from view |	https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/post-busola-integration-test-k3s/1484534492138835968 |
| test-dns-providers.spec.js	| Expected to find element: `:visible`, but never found it |	https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/post-busola-integration-test-k3s/1485613113981014016 | 
| test-jobs.spec.js 	| Expected to find content: '/test-job-25923317-/' within the element: \<body> but never did.	| https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/post-busola-integration-test-k3s/1486324308933349376 |
| test-statefulsets.spec.js |	Expected to find content: 'kyma-system' within the element: \<body> and with the selector: 'a' but never did.	| https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/post-busola-integration-test-k3s/1484099914555199488 |

**Comment by dariadomagala** [comment]
Fix will be handled in https://github.com/kyma-project/busola/issues/902
