### ISSUE TITLE
SPIKE:  ?watch=true parameter in api calls instead of polling

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#985]
Research the use of ?watch=true parameter in api calls instead of polling.

Acceptance Criteria

- [x] Evaluate if we can use ?watch
- [x] Evaluate and document the Performance Gains / Losses and possible scaling issues when we use ?watch

**Comment by Sawthis** [comment]
Estimation: 2 PD

**Comment by wchrapka** [comment]
PR [1019](https://github.com/kyma-project/busola/pull/1019) prototypes fetching the resource lists with watch instead of short polling. The performance was stress-tested with test being the equivalent of 50 users having a list open for 2 minutes, while listed items were being modified. The biggest relief was noted at the proxy level. Repeating requests totalled at 482 MB transferred. Long polling took 20 MB.

![image](https://user-images.githubusercontent.com/94044629/156003381-99dac53c-a251-472f-abbf-60902418389f.png)

**Comment by wchrapka** [comment]
Steps to consider:
1. Examine why tests are not passing (discrepancies between local and CI tests occur)
2. Verify if incomplete chunks are served correctly. Sometimes k8 divides a record into 2 or more chunks.
3. Remove useGetList hook and its usages
4. Apply similar solution for useGet, the hook that is used for short polling resource details
